spring.application.name=freelancer-platform
spring.datasource.url=jdbc:mysql://localhost:3306/freelancer_platform
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true